### ISSUE TITLE
Captions box positions

### ISSUE THREAD

**Issue by jmytch** [ratwithacompiler/OBS-captions-plugin#1]
Is it possible to add settings where we can put the captions box on far right of the screen, or far left of the screen? At the moment captions box are in the middle which take over lot of game's subtitles when a character or two is talking, captions pretty much covers it there. Would be nice to have a option to move the captions box on far right of the video player?

Current CC covers the game subtitle in the center;
![Screenshot 2019-07-26 at 6 49 35 PM](https://user-images.githubusercontent.com/45726972/61939273-3cd58880-afd6-11e9-89f4-16b3d3dae326.png)

What it should look like if there is setting to move the captions box on far right as this as an example;
![Screenshot 2019-07-26 at 6 36 01 PM](https://user-images.githubusercontent.com/45726972/61938397-52e24980-afd4-11e9-8ff1-976d17570a13.png)

![Screenshot 2019-07-26 at 6 38 35 PM](https://user-images.githubusercontent.com/45726972/61938520-a8b6f180-afd4-11e9-8b9c-0e28c7edec97.png)

**Comment by ratwithacompiler** [comment]
Unfortunately not, the positioning of the captions is completely out of my control. With this plugin OBS basically just sends the captions as text as a subtitle track and all the display aspects of it are handled by the video player itself, so viewers only get whatever options Twitch provides in their player which isn't much. 

Viewers can move them a little bit currently between top/bottom and left/right via `Gear Icon -> Closed Captions Options -> Text` but those settings don't really do much either. The only way to change that with the way this plugin works would be for Twitch itself to simply add more options to their player.

It's an unfortunate tradeoff, with the native captions you get VOD support but no customisability at all with how they look from the dev side or streamer side but with Twitch Extensions you don't get VOD support.

I'll add that to the Downsides to make that clearer.

**Comment by jmytch** [comment]
Oh okay. With FrankerFaceZ they could override and put in any position we want it to as it works with your captions but I don't think you use CSS code? Here the source to it;
https://github.com/FrankerFaceZ/FrankerFaceZ/blob/master/src/sites/twitch-twilight/modules/player.jsx

CTRL + F search for Closed Captioning

**Comment by ratwithacompiler** [comment]
Sorry I forgot to reply to this but I added the link to FFZ in the readme back then so it's easier for people to find, thank you!
