### ISSUE TITLE
Cannot load OBS-captions-plugin after updating to OBS . 24.0.5 

### ISSUE THREAD

**Issue by lmarches** [ratwithacompiler/OBS-captions-plugin#11]
Hi There, thanks a lot for the plugin! 

Unfortunately there's a problem with an image not found? Bizarre..same issue in other plugins btw. 

Thanks!!

`error: os_dlopen(/Applications/OBS.app/Contents/Plugins/libobs_google_caption_plugin.so->/Applications/OBS.app/Contents/Plugins/libobs_google_caption_plugin.so): dlopen(/Applications/OBS.app/Contents/Plugins/libobs_google_caption_plugin.so, 257): Library not loaded: @rpath/QtWidgets
  Referenced from: /Applications/OBS.app/Contents/Plugins/libobs_google_caption_plugin.so
  Reason: image not found

warning: Module '/Applications/OBS.app/Contents/Plugins/libobs_google_caption_plugin.so' not loaded`

**Comment by ratwithacompiler** [comment]
Added a fixed version for OBS 24 to the releases, thanks for the report!
