### ISSUE TITLE
OBS recordings, render to a source?

### ISSUE THREAD

**Issue by kylane** [ratwithacompiler/OBS-captions-plugin#114]
Firstly, thanks for this plugin - I work in accessibility, and this is looking so hopeful!

In lieu of steaming to twitch, is there a way to render the caption output to a source for recording or virtual camera sessions?

**Comment by ratwithacompiler** [comment]
The plugin can output the captions to any OBS text source you have so it's just part of the video directly, see Open Cations tab in the plugin settings.

**Comment by kylane** [comment]
Thanks for that @ratwithacompiler - makes sense once you know!
