### ISSUE TITLE
Text Sources for Open Captions can't find new (v3) GDI sources made in 30.2

### ISSUE THREAD

**Issue by WebsterLeone** [ratwithacompiler/OBS-captions-plugin#137]
Text sources made prior to 30.2 are able to be selected from the Text Source drop-down under the Open Captions setting, but text sources made in 30.2 do not show up in the drop-down. I have confirmed this with two other people having the exact issue.

From the scene JSON file, here's a working one:

> {
"prev_ver":503447552,
"name":"Captions-Vertical",
"uuid":"-",
"id":"text_gdiplus","versioned_id":"text_gdiplus_v2",
"settings":
{
	"extents":true,
	"font":{
		"face":"OpenDyslexic","style":"Regular","size":72,"flags":0
	},
	"valign":"bottom","opacity":100,"bk_opacity":95,"extents_cx":400,"extents_cy":900,
	"text":" "
},
"mixers":0,"sync":0,"flags":0,"volume":1.0,"balance":0.5,"enabled":true,"muted":false,
"push-to-mute":false,"push-to-mute-delay":0,"push-to-talk":false,"push-to-talk-delay":0,
"hotkeys":{},
"deinterlace_mode":0,"deinterlace_field_order":0,
"monitoring_type":0,
"private_settings":{}
}

Here's a non-working GDI source
>{
"prev_ver":503447552,
"name":"Test Text",
"uuid":"-",
"id":"text_gdiplus","versioned_id":"text_gdiplus_v3",
"settings":
{
	"text":" ","extents":true,"chatlog":false
},
"mixers":0,"sync":0,"flags":0,"volume":1.0,"balance":0.5,"enabled":true,"muted":false,
"push-to-mute":false,"push-to-mute-delay":0,"push-to-talk":false,"push-to-talk-delay":0,
"hotkeys":{},
"deinterlace_mode":0,"deinterlace_field_order":0,
"monitoring_type":0,
"private_settings":{}
}

(UUIDs have been scrubbed)

**Comment by ratwithacompiler** [comment]
Thanks for the report, fixed in new release (hopefully).
