### ISSUE TITLE
Different Tools Menu...

### ISSUE THREAD

**Issue by Gherkinwarrior** [ratwithacompiler/OBS-captions-plugin#2]
In my tools section I have ''Elgato Remote control for OBS Studio'' 
I run OBS 23.2.1 (64x)

Any ideas, hos?

**Comment by ratwithacompiler** [comment]
If there's no option for it then it's probably not installed correctly, maybe put in the wrong folder?
it should be in `OBS_FOLDER\obs-plugins\64bit\obs_google_caption_plugin.dll`

if it's in the right place maybe check the log file if there was some error.

**Comment by cygnatus** [comment]
Most likely you put the file(s) in `\bin` instead of `\obs-plugins`.

I may or may not have done the same, and putting it in the right folder(s) fixed it.
