### ISSUE TITLE
Add instructions for installing plugin on the Mac

### ISSUE THREAD

**Issue by adamlogan** [ratwithacompiler/OBS-captions-plugin#20]
To install the plugin on the Mac navigate to the OBS App in /Applicatoins/. Right click on OBS.app , select "Show Package Contents" > Contents > Plugins.  Drop .SO file into the Plugins directory.

**Comment by ratwithacompiler** [comment]
sorry haven't been active on this for a while, added Mac instructions now.

**Comment by adamlogan** [comment]
Thanks dude, guess I should learn how to use github and request a pull. Just trying to make life easier for others like me trying to make videos accessible with a non-existent budget. Someday I hope I can help the work of people like you.
