### ISSUE TITLE
CC when Recording Only

### ISSUE THREAD

**Issue by mlong-1958** [ratwithacompiler/OBS-captions-plugin#22]
It would be very handy to be able to CC when just recording rather than streaming.

**Comment by remyje** [comment]
You'll want to do open captions of some kind then, using a browser source to a third party captioning site, instead of this.  This is for closed captions, which are encoded into the RTMP stream and are not part of the rendered video in OBS.

**Comment by ratwithacompiler** [comment]
It does support captions on recordings as well which are embedded in the video file and not in the RTMP stream. Just set it to "Output to"  "Recordings"  or "Stream and Recordings".
However that only works with some of the recording file formats OBS has and can only be played with few video players. MPV definitely works, I think VLC too but I'm not sure.

I do plan to add saving to separate .txt and hopefully .srt captions files soon too to make saving captions for recordings easier but that might take a bit (at least for .srt files).
