### ISSUE TITLE
Plugin not showing on Mac

### ISSUE THREAD

**Issue by celinenicolas** [ratwithacompiler/OBS-captions-plugin#26]
I installed the plugins on Mac, but nothing shows up in Tools after restarting OBS Studio.

OBS Studio 25.0.8
Mac OS Catalina 10.15.4

**Comment by ratwithacompiler** [comment]
It should work on Mac normally, there are clearer install instructions in the readme now for Mac too: https://github.com/ratwithacompiler/OBS-captions-plugin

**Comment by designbymichael** [comment]
The instructions don't work for me, Mac OS version 12.3.1 (Monterey), specifically with the M1 chip.  I followed the instructions to the letter and the plugin does not show up under the tools menu in OBS.
