### ISSUE TITLE
Should the captions appear in my Progam window when streaming

### ISSUE THREAD

**Issue by EmanonZero** [ratwithacompiler/OBS-captions-plugin#27]
I have installed the plugin and tested it and it works, when streaming and looking at my recording using Windows Media player I cannot see the captions, also Twitch is not seeing them.

Any ideas?

Thanks

**Comment by remyje** [comment]
The captions are encoded into the RTMP stream sent to Twitch.  They do not appear in the OBS preview window and so of course will not be included in any local recordings or saved replays.

On the Twitch side, you have to enable captions in the UI to see them.  They are "closed captions" not "open captions".

**Comment by ratwithacompiler** [comment]
You should be able to see a preview of the captions text in the preview window (Tools -> Cloud Closed Captions) or via the Captions Dock (View -> Docks -> Captions). If you see them there they should work on Twitch too. However it does not currently seem to work with the AMD hardware encoder so if you're using that then that could be the issue.

For local recordings they do get embedded too if you use .ts files but almost no video players play them correctly, only really MPV does.
