### ISSUE TITLE
Open Caption Support [Feature Request]

### ISSUE THREAD

**Issue by savethebologna** [ratwithacompiler/OBS-captions-plugin#28]
An open caption source option would be excellent (alongside something like the VirtualCam plugin) to allow captioning in other applications, such as Zoom. It would enable Zoom/Meet/etc meetings for hard of hearing communities.

**Comment by remyje** [comment]
This is specifically for encoding the captions into the RTMP stream.

You can use one of the existing methods for using third party captioning (like Web Captioner, etc) sites as a browser source in OBS and overlay it on a full screen camera source.  Then create a virtual camera in OBS and use that as the camera in Zoom or whatever you are using to give you Open Captions.

**Comment by ratwithacompiler** [comment]
I already implement Open Caption support via OBS text sources a while ago but am still testing that currently. A public release of that should be out soonish. 

But yes https://webcaptioner.com/ is very nice for open captions in OBS in the meantime.

![open captions](https://user-images.githubusercontent.com/52238970/86445195-42713d80-bd12-11ea-99f1-3e8e14ccd605.png)
