### ISSUE TITLE
Creating google API key

### ISSUE THREAD

**Issue by tt2468** [ratwithacompiler/OBS-captions-plugin#29]
Hi all,

I've been experimenting with this plugin on linux, and I'm wondering- How do I create a google API key for captions? I haven't been able to find any guides on it at all, and the latest linux builds in CI have an empty "API Key" section. 

Thanks

**Comment by ratwithacompiler** [comment]
Creating API keys can be a bit complicated but there's a linux beta build in releases now for testing https://github.com/ratwithacompiler/OBS-captions-plugin/releases/tag/v0.0.12b
