### ISSUE TITLE
Transcript Output

### ISSUE THREAD

**Issue by lostchocolatelab** [ratwithacompiler/OBS-captions-plugin#3]
Is there an output stored anywhere that includes the text output of the subtitling/ transcript generated by the Speech-to_Text? Would be great to grab that after the fact and leverage for further accessibility. Thanks for your efforts so far!

**Comment by ratwithacompiler** [comment]
Basic transcript  saving is added now, should be in the next release, thx!

**Comment by lostchocolatelab** [comment]
Thanks for the addition of this feature, the Preview window and ability to Select/ Copy is pretty great.

I haven't been able to find any of the transcript outputs...is there a default folder set for the .txt files that are output?

I see this in code: "obs_data_set_default_string(load_data, "transcript_folder_path"...but not in the Caption Settings? 

Thanks for the further guidance!
