### ISSUE TITLE
Feature Request: Hard Coded subtitles for some front end players

### ISSUE THREAD

**Issue by matsura8** [ratwithacompiler/OBS-captions-plugin#31]
Is there some way to add the subtitles into the video processing, in case the site we are streaming to does not have subtitles enabled in their player?

**Comment by ratwithacompiler** [comment]
I implemented Open Caption support via a text source a while ago, there's a beta version out now with support for that: https://github.com/ratwithacompiler/OBS-captions-plugin/releases

**Comment by matsura8** [comment]
Awesome. Works great! Appreciate it. Can you please set up a donation box so I can donate to this project?
