### ISSUE TITLE
Is there any way to send request to Google Cloud API through proxy?

### ISSUE THREAD

**Issue by eternalphane** [ratwithacompiler/OBS-captions-plugin#32]
Hi, I'm currently in mainland China and I cannot access google api without using a proxy server. It would be a lifesaver if you could add a proxy setting, or at least respect the global proxy settings.

edit: If you are busy right now, could you please guide me to the right way to make it? I thought it might be some code under `lib/caption_stream/speech_apis/google_http_older`, but I'm not really sure.

**Comment by ratwithacompiler** [comment]
Hi, sorry didn't see that until now, but no currently there's no way to set a proxy for the plugin (I don't think OBS itself even supports proxies atm) and I'm not sure how I would go about implementing that tbh.

Currently captions are received via lib/caption_stream/speech_apis/google_http_older/TcpConnection.cpp which is a simple wrapper around sockets so you would have to add support for proxies there I think.

But using something like Proxifier/proxychains/Proxycap that allows you to proxy any TCP connection would probably be much easier and usable for anything including OBS itself.
