### ISSUE TITLE
Possible to add a translation option?

### ISSUE THREAD

**Issue by reedog117** [ratwithacompiler/OBS-captions-plugin#40]
Would it be possible to add a caption translation option?

Possible use case - an English-speaking person traveling abroad in Japan. The caption plugin is configured for Japanese and then a translation API translates the Japanese into English, similar to the auto-translating captions that you find on YouTube.

**Comment by ratwithacompiler** [comment]
Probably not possible in the short term. Google has a translation API but it's pretty expensive so not really an option. There are some open source projects that are making good progress, Mozilla has a very promising looking one that I hope will be good enough to be useable at some point but nothing in the near future that I'm aware off, so currently not really possible.
