### ISSUE TITLE
Captions work fantastic during the stream to twitch, but the srt file doesn't output to the set folder?

### ISSUE THREAD

**Issue by ArpMichaelB** [ratwithacompiler/OBS-captions-plugin#41]
With my most recent stream, the captions are coming across on twitch just fine, but when I finished the stream and remuxed the recording from flv to mp4, the caption SRT file was nowhere to be found! Seemingly, the mp4 has a caption stream embedded, but it's entirely empty, rather than containing the (noticably rock-solid, by the way) captions! Would love to get this resolved so I can tack those captions onto my Youtube VOD that I upload. I can upload and link the OBS Log file from the appropriate stream session if necessary!

**Comment by ratwithacompiler** [comment]
Hi, yes log file would be great

**Comment by ArpMichaelB** [comment]
[https://drive.google.com/file/d/12-61mfjyNxO5GZqYHYkOhhj0RiSSkmQR/view?usp=sharing](url) Here's the link!

**Comment by ratwithacompiler** [comment]
Weird, seems it didn't even attempt to save them based on the log. 

Do you have all of:
`Save Transcripts` checked
`Save For` Streams  (or Streams + Recordings) selected
and a Transcript Folder set

in Transcript settings?

**Comment by ArpMichaelB** [comment]
Ah, it's always the little things! Thought I had save transcripts checked, turns out it wasn't!

**Comment by ratwithacompiler** [comment]
Yeah it's kinda confusing UI wise tbf, I changed it now for the next version so all the actual settings are greyed out and not editable unless the main checkbox is checked so it's more clear.
