### ISSUE TITLE
subtitle settings

### ISSUE THREAD

**Issue by awistudio** [ratwithacompiler/OBS-captions-plugin#44]
I have a problem with long text.
too long intervals.
and a lot of text displays.
what should i change?
![2020-09-28_23-30-42](https://user-images.githubusercontent.com/60708776/94488486-fb94c600-01e2-11eb-9ad5-6359a31c175d.png)

e.g

3
00:01:09,892 --> 00:02:09,437
long text
4
00:02:09,699 --> 00:03:09,548
long text
5
00:03:09,989 --> 00:04:09,371
long text
6
00:04:10,422 --> 00:04:50,395
long text

**Comment by awistudio** [comment]
in the recording file .srt

**Comment by ratwithacompiler** [comment]
That's currently not really possible sorry. So the way the google API works is it returns the results basically sentence by sentence and if they are shorter than the srt settings that are set it will combine some together to longer ones but if there's just a single sentence that's really long by itself it will not split it up. So if you talk a lot continuously without any breaks it will basically just be as long as the sentence was regardless of how short it's set in the settings. 

I do plan to add splitting single sentences at some point but timestamp wise that's not that easy to get right.
