### ISSUE TITLE
how to compile wthout Ci 

### ISSUE THREAD

**Issue by Zlywilk** [ratwithacompiler/OBS-captions-plugin#46]
hi,
 I'd like to know how to compile this plugin on windows or linux because i try test custom version  without diacritical marks
greeting from poland
Wiktor

**Comment by ratwithacompiler** [comment]
You can check out the Windows CI setup to see how to fully build it:
https://github.com/ratwithacompiler/OBS-captions-plugin/blob/master/CI/install-script-win.cmd

but basically it needs 3 important paths to work
-DOBS_SOURCE_DIR
-DOBS_LIB_DIR
-DQT_DIR

OBS_SOURCE_DIR: Path to OBS sources root (as cloned from the OBS repo) used to include OBS headers
OBS_LIB_BIN_DIR: Path to a compiled build of OBS, will be used to link against 
QT_DIR: Path to a QT version to include and link against

You can either create those yourself by compiling OBS yourself or download the ones that I use for my CI setup from here:
https://dev.azure.com/ratwithacompiler/OBS_plugin_deps/_build/results?buildId=159&view=artifacts&type=publishedArtifacts
