### ISSUE TITLE
possible to transport lang used ?

### ISSUE THREAD

**Issue by Niko78** [ratwithacompiler/OBS-captions-plugin#51]
hi
I use with succes your plugin and it works very well.
I have just a small problem is that language doesn't seem to be integrated in stream (I use wowza as server)
... so in the end on player, I have CC button without language information.
Is it an error on my side or language selected in settings is not inside stream ?

thanks
Niko

**Comment by ratwithacompiler** [comment]
Hi.

Captions are embedded into the stream via OBS itself which currently does not support any way to set what language they are in as far as I know so I don't think thats currently possible.

**Comment by Niko78** [comment]
hi,
fyi, I opened a case in wowza support about your plugin/obs sending stream rtmp to wowza cause I have difficult to get lang.
They answered that after few tests :
"Based on your results (all good with the cea608 sample file and the issue happening only when generating/sending the cea608 captions from the OBS plugin), everything points to the plugin not generating fully compliant cea608 captions. Also note that it's in beta, thus likely to be not fully tested. At this stage, I'd recommend reaching out to the plugin developers for their review, since the plugin's output should be in exactly the same format and compliance level as the cea608 sample file I've provided, which doesn't seem the case at the moment."

What do you think ? cea608 can transport lang info
I added the file provided by wowza support team to test if that can help
Thanks

https://user-images.githubusercontent.com/17108017/103292460-1c410780-49ee-11eb-8f82-c5108cbca510.mp4

**Comment by ratwithacompiler** [comment]
Hi, like mentioned above the actual CEA 608 embedding of the captions into the stream is done by OBS itself via libcaption, my plugin just handles the speech recognition API and utility stuff like transcripts and then basically just passes the caption text on to OBS for embedding.

Any changes like fixing CEA compliance bugs or setting a language would have to go into OBS and libcaption itself and are out of scope here.

**Comment by tvadi** [comment]
I think the fix is here..

[https://github.com/stoth68000/libklvanc/issues/68](url)
