### ISSUE TITLE
Foreign Character Romanization?

### ISSUE THREAD

**Issue by DavidSalsburg** [ratwithacompiler/OBS-captions-plugin#53]
You say all foreign character sets aren’t supported by Twitch/OBS’s caption systems, so are there any plans to translate foreign character set languages by romanizing the translations to the standard alphabet?

**Comment by ratwithacompiler** [comment]
No plans for that currently, no. It seems it would be only usably doable for a couple languages and take quite a bit of time that I don't really have.

For Twitch currently I usually suggest either open captions or using an extension like https://stream-cc.gooseman.codes/ for foreign languages as extensions don't have the same limitations as native CC.
