### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by cerpintext** [ratwithacompiler/OBS-captions-plugin#54]
OBS Studio, the only relevant lines I found in the log are these. 
```
Windows Version: 10.0 Build 18363 (release: 1909; revision: 1256; 64-bit)
OBS 26.0.2 (64-bit, windows)
Running as administrator: true
```

This is the 64bit dll plugin from latest release, inside `obs-studio\obs-plugins\64bit` (the 32bit is in the 32bit folder) just to show its in the right place according to the readme. No sign of it in the OBS Studio startup log or tools tab though.
![image](https://user-images.githubusercontent.com/27957371/101909152-60927200-3bbd-11eb-8ddd-597aa725f187.png)
![image](https://user-images.githubusercontent.com/27957371/101910182-de0ab200-3bbe-11eb-8c97-1cf35ab41939.png)

**Comment by cerpintext** [comment]
brb pressed enter didnt expect it to send the issue :)

**Comment by cerpintext** [comment]
Added the dll to this path instead adds it properly (seemingly): `obs-studio\bin\64bit` 
Is this intended procedure with newest version?

**Comment by ratwithacompiler** [comment]
That's weird, the first path should be right. Just normal official OBS from their website and installer I assume? 
Not sure why that doesn't work. Mine's at `C:\Program Files\obs-studio\obs-plugins\64bit\obs_google_caption_plugin.dll` currently.

**Comment by cerpintext** [comment]
hmm, it might be a scuffed reinstall way back that caused the issue.
Attached is a my obs-studio in a tree format if that can help just quickly compare the layouts.
(sorry about the horrible formatting)
[obs-studio-tree.txt](https://github.com/ratwithacompiler/OBS-captions-plugin/files/5683229/obs-studio-tree.txt)

**Comment by cerpintext** [comment]
oh and yes, using the normal OBS Studio installer from their website, so correctly assumed

**Comment by ratwithacompiler** [comment]
That's mine:
[my-tree.txt](https://github.com/ratwithacompiler/OBS-captions-plugin/files/5711646/my-tree.txt)

weird, looks like the install is doubled in bin/64bit in yours or something 🤔
