### ISSUE TITLE
Problems saving SRT files in C:/

### ISSUE THREAD

**Issue by tatunts** [ratwithacompiler/OBS-captions-plugin#58]
Hello @ratwithacompiler !

First of all, thank you very much for all your work here... Really appreciate it :)

I'm having some problems trying to save my transcripts after a local recording... I've set the save path to the same path as the recorded videos goes to. I'm running a portable version, so to not loose my OBS configuration (media paths), I always put them at my `C:/` location.

The recordings are set to `C:\OBS MuvRH Portable\my stuff\Recordings` but they do not show up there after I finish recording. When I set the transcript path to another folder, my desktop, for example, it works perfectly.

I've tried to run OBS as admin but no luck...

Any ideas how to solve this? This would be very useful for me, since I'll have both the video recording and the subtitles, side by side, same filename and I can use this portable OBS version in more than one PC :)

Thanks a lot!

**Comment by ratwithacompiler** [comment]
Hi!

Can you upload a logfile from OBS taken from when it doesn't work?

`OBS -> Help -> Logs -> View current logs` (or something similar sounding) to open the logs folder which should have the last 10 or so runs of OBS.

**Comment by tatunts** [comment]
Hello!

Here's the latest log.

[2021-03-11 18-07-27.txt](https://github.com/ratwithacompiler/OBS-captions-plugin/files/6126244/2021-03-11.18-07-27.txt)

Since my OBS is half configured in English and Brazilian Portuguese, I've changed the above recording path to English, so you could understand it better. Maybe this issue has something to do with special characters? I've seen this in the log file: `GravaÃ§Ãµes`, it was supposed to be `Gravações`...

Thanks!

**Comment by tatunts** [comment]
So, yeah, it was the special character @ratwithacompiler ...

![image](https://user-images.githubusercontent.com/25224882/110871866-f36ea580-82ad-11eb-8de7-6a7e5b8fbdfd.png)

No worries, I'll just change the recording path.

Thank you!

**Comment by ratwithacompiler** [comment]
I didn't test special chars on the Windows version, will fix that for the next release, thanks for the report!

**Comment by tatunts** [comment]
No worries! I’m glad I could help in any way :)
