### ISSUE TITLE
The captions doesn't work 80% of the time in French (Canada) language

### ISSUE THREAD

**Issue by Fireztonez** [ratwithacompiler/OBS-captions-plugin#6]
1036/5000
I wanted to add subtitles to my French Twitch channel, but currently, with your OBS plugin for some reason it does not seem to work at all 80% of the time. When I watch the subtitles on my channel, there is one or two phrase with Close-Captions and then have 10 minutes where there have nothing at all (And I talk pretty mutch none-stop!!).

I was expecting some incoherence or errors in the transcripts, but at least something. But currently the bit that is transcribed often contains errors and the majority are absolutely not, which makes the stream totally incomprehensible without sound.
In addition, there seems to be a delay of sometimes almost 10 seconds between the moment I say something and the Close Captions, just question to makes the whole thing even worse !!

I do not know if you are able to work to improve your system of transcriptions for French Canada or if it is the engine used which is just absolutely terrible and you have no control over it? Or possibly I have somes wrong config on your plugin??

Here's the capture of my setting page:
![image](https://user-images.githubusercontent.com/19277301/66724417-d9e4d800-edf3-11e9-8e71-edd0dc13e0b5.png)

### Setup Informations:
**Operating System:** Windows 10 (64 bits) 1903
**OBS:** OBS Studio 64 bits v24.0.3
**OBS Captions Plugin:** v0.0.10

Microphone AT-2020 XLR plugged in Behringer UMC22 USB Interface and controlled by VB-Audio VoiceMeeter Potato

Fireztonez

**Comment by ratwithacompiler** [comment]
Thanks for the detailed report, I tested with some audio and get similar results so not an issue on your side, looks like the speech recognition is just pretty bad with this language. 

Yeah unfortunately I don't really have any control over it, I just get whatever the speech API gives me so nothing I can really do there, sorry.
