### ISSUE TITLE
Captions not appearing on stream?

### ISSUE THREAD

**Issue by cfargeix** [ratwithacompiler/OBS-captions-plugin#61]
Hello, I just downloaded the plug-in so I'm on the most updated version and I also use Streamelements OBS.Live version 26.1.1.

I've been having trouble getting the captions to appear on the stream on Twitch. The caption preview is working fine and the captions button appears on my stream most of the time, but the captions themselves are not appearing.

I reached out and I'm not the only person who's had this issue and it seems like it may have just started after the last OBS update?

**Comment by Pinkyyyy** [comment]
same issue here, they dont even show up for me on the example vod

**Comment by Pinkyyyy** [comment]
a workaround is to just use open captions, those still work

**Comment by cfargeix** [comment]
> a workaround is to just use open captions, those still work

What do you mean? It asks for a text source and I don't have any?

**Comment by Pinkyyyy** [comment]
yeah you add a text source, i named mine captions, go to caption settings, click open captions, enable text source output, click that text source, and when you start streaming (for testing i use the bandwidth test mode) you should see that text source generating your captions

**Comment by ratwithacompiler** [comment]
Ohh yeah looks like they broke captions on the website player.

broken on player: 1.3.0-twitch.4-rc.2-web.4
still working ok on: 1.3.0-twitch.web.1-e475f8a4  (⚙ -> advanced -> video stats to see backend version)

Which one you get seems kinda random when trying in incognito a couple times, I guess they are still testing that version. Not really sure how to make the right people at Twitch aware of that, the only accessibility person I knew there isn't with Twitch anymore. I tweeted @TwitchSupport about it, hopefully they'll forward that ...

Thanks for reporting!

**Comment by tonyjin** [comment]
Twitch video team chiming in. Thanks for the report, we've reverted our player deployment for now.

**Comment by ratwithacompiler** [comment]
@tonyjin Thank you for the quick action!
