### ISSUE TITLE
Self compiled and built .dll doesn't work

### ISSUE THREAD

**Issue by vikasTmz** [ratwithacompiler/OBS-captions-plugin#64]
OS: Windows 10
OBS version: 26.1.0

Issue: *"No caption is generated using the obs_google_caption_plugin.dll built from source, but the ones provided under GitHub releases work"*

Steps:

- Built OBS 26.1.0 from source.
- Edited following lines in `CI/http/win-install-script.cmd`:
-DOBS_SOURCE_DIR='<path/to/obs-26.1.0>' ^
-DOBS_LIB_DIR='path/to/obs-26.1.0/build' ^
-DQT_DEP_DIR='path/to/Qt/5.15.0/msvc2019_64'

- Ran `win-install-script.cmd`
- Moved the obs_google_caption_plugin.dll generated under `release\Closed_Captions_Plugin__v0.18b_Windows\obs-plugins\64bit` to `C:\Program Files\obs-studio\obs-plugins\64bit`
- Caption Plugin is visible but on enabling and choosing an audio source, no caption is generated. Reproducing the same steps but with the .dll provided in your release works for me.

I guess the question should be: Did I miss something in the building the plugin on my own?

**Comment by ratwithacompiler** [comment]
If the plugin works and is visible you're probably missing the API key, either build it with -DGOOGLE_API_KEY=a_speech_api_enabled_key or set it in the settings field (which shows up if it's not built with a key).

Also you wanna build the GRPC version not the old http version (`CI/grpc/win-install-script.cmd`).
That also needs GRPC libs and google speech api protos to work, the CI script (see `Windows_GRPC` job in `azure-pipelines.yml`) just downloads those from my other repo here: https://github.com/ratwithacompiler/obs_plugins_CI_deps/runs/2090780091 artifacts direct link: https://dev.azure.com/ratwithacompiler/OBS_plugin_deps/_build/results?buildId=688&view=results 

Then it should work.

**Comment by vikasTmz** [comment]
Thanks for the reply!

I saw in one of the issues that new API keys from GCP don't work anymore, is that true? I tried building it with a new key I generated but it doesn't work (generated the key using Cloud Speech-to-Text API).

I will try building it with grpc; if possible in a line or two, what major difference would I observe between the two protocols? - performance? reliability? 

Also, from your discussion with @noopkat in https://github.com/ratwithacompiler/OBS-captions-plugin/issues/4, I was wondering if it is possible to get the captions retrieved by your native plugin via python scripting (*I could move this to a new issue if needed*).

**Comment by ratwithacompiler** [comment]
Yeah the http one is deprecated so you need to use GRPC one with new keys, they just don't work on the old endpoint, other than that it's pretty much the same apart from more options on the new one.

Currently the plugin doesn't have any way for scripting to access the results no. I'm not sure if there's any good way to do that either really, at least I'm not aware of anything in OBS that would let plugins do that nicely.

But if you wanna caption with google from python you can just use something like https://pypi.org/project/SpeechRecognition/  They have some nice examples for captioning a mic with Google Speech Recognition in just a couple lines of code.

**Comment by vikasTmz** [comment]
> But if you wanna caption with google from python you can just use something like https://pypi.org/project/SpeechRecognition/ They have some nice examples for captioning a mic with Google Speech Recognition in just a couple lines of code.

Cool. So I'll need to figure out how to get the audio source from OBS in python. Looking through @upgradeQ's examples, but if you know a good source, I would really appreciate it.
