### ISSUE TITLE
Audio resamples to 16KHz from 48KHz

### ISSUE THREAD

**Issue by ggrefrakt** [ratwithacompiler/OBS-captions-plugin#69]
Is there any way to prevent audio resampling from 48KHz to 16KHz? I would assume this only applies to the Mic source which is having the captioning done to it, however I notice a severe degradation to sound quality when using this plugin. I would prefer to keep my default audio sample rate of 48KHz, but it seems there is no way I can achieve this.

**Comment by ratwithacompiler** [comment]
The plugin should not affect the audio quality on stream in any way. It internally resamples the mic audio to 16KHz for sending it to the captioning service but that should have no effect on anything else.
