### ISSUE TITLE
Problem with saving as a srt-file / import in Adobe Premiere

### ISSUE THREAD

**Issue by GenkiDerHusky** [ratwithacompiler/OBS-captions-plugin#72]
When I use the plugin, the captions are almost in real-time on twitch. When I save it as a srt-file: I got every 20 – 30 seconds, a section full of words that I’ve said in this time. Is it possible to save the srt-file like the captions on twitch? **So, that I am able to import the file in Adobe Premiere and have only five words that I say and then the next one?** I mean that the system will save it more like it was in the livestream / recording and I don’t have to waste my time to move all the words to the right positions?

**I attach a screenshot from an example of the srt-file.**
![SRT_file_preview](https://user-images.githubusercontent.com/88197598/127675342-4dc78bad-2eaf-4f07-9ee1-830b10161bed.png)

**And I need it like:**

1
00:00:00,0 --> 00:00:02
This is a test

2
00:00:03 --> 00:00:05
Is this possible?

**Comment by ratwithacompiler** [comment]
Added an option to have it split individual sentences too now if they are too long (which it previously didn't), should fix this, will be in the next release.
