### ISSUE TITLE
Multiple Open Captions on different text source

### ISSUE THREAD

**Issue by holypunisher** [ratwithacompiler/OBS-captions-plugin#75]
Currently we have only one text source to set as open caption in our streams, I would like the option to have multiple text source to output to so that I can set the different font and/or colour for the same text being recorded from an input e.g. microphone and to adjust the line length and count to each of them as well. Not sure what is the technical limitation for this but I was thinking of setting up scene that uses the caption but needs to be set up as per the space 
i.e. a scene that looks like a comic page would need to squeeze the text on the speech bubbles while I still want to use the caption like everyday subtitles so I would probably need 2 text source to output to. 

Do let me know if there is a better way to do this

**Comment by ratwithacompiler** [comment]
Added support for that, should be in the next release.
