### ISSUE TITLE
Usage of your code in a personal project.

### ISSUE THREAD

**Issue by PedroSPSantos** [ratwithacompiler/OBS-captions-plugin#88]
Hello to the both of you!

Firstly say that this is an amazing project you have been running and I have to congratulate you on this amazing plugin!

I have a question: Can I use your current code as a basis to do a plugin of my own that uses the closed captions in the current way you have and even enhances it? Or at least to study how the current closed captions plugin works and do something even better on my own?

In case of me using it to do my own with basis on your own code, there would be the references saying the basis of my code would be yours and dont want get any monetary adavantages with this plugin I m gonna create.

Any questions or something you want to understand either respond here or even schedule a meeting if needed :)

Best Regards,

Pedro Santos

**Comment by ratwithacompiler** [comment]
The plugin is released under GPL 2 so you're free to use code from it or make your own plugin based on it under the terms of the license. Have fun!
