### ISSUE TITLE
Windows 64 install does not include Cloud Captions options for setup

### ISSUE THREAD

**Issue by HighPotential1** [ratwithacompiler/OBS-captions-plugin#92]
Hoping I can get this working, it sounds awesome! Upon install the Captions (experimental) window is visible with only three options plus enable. Decklink captions and output also there, with no source available in the decklink source drop down and no functionality in the output. Clicking start on output or preview does not activate anything, and a small warning at the bottom says keyer output requires RGB mode in advanced (which does not respond to changing the RGB mode). Most tutorials I see have the setup occurring in a cloud captions tool bar option which i do not seem to have. I have tried all versions (old and most recent) with the same result. any advice is appreciated!

**Comment by ratwithacompiler** [comment]
Maybe it copied into the wrong directory?
The `obs_google_caption_plugin.dll`  file should effectively end up in `C:\Program Files\obs-studio\obs-plugins\64bit\ ` assuming default OBS install location.

You can also check OBS logs to see if it had any issues loading the plugin  OBS Menu: Help -> Log Files -> Show Log Files
