### ISSUE TITLE
Google API Key

### ISSUE THREAD

**Issue by ebagot** [ratwithacompiler/OBS-captions-plugin#95]
Hello, 

I'm sorry, it's not really a question about the project in itself. 

I'm a member of a french association that helps people doing and hosting podcasts and we wish to use Google Speech to Text to make them accessible to the hearing impaired. The problem is that it's too expensive for the association's budget. 

You seems to use Google Speech to Text API with no restriction. We would like to know how it that possible for you to offer it's use in a free OBS extension. Are you paying the bill for everyone or is it a way to obtain a Google API Key in any other way ? 

Thank you in advance for your response.

**Comment by ratwithacompiler** [comment]
Hi, plz contact me via email if you want a good answer to that,  just  [my github username] @gmail.com
