### ISSUE TITLE
Access to caption track, option to send SRT instead of live captioning?

### ISSUE THREAD

**Issue by bost-ty** [ratwithacompiler/OBS-captions-plugin#97]
Hi RWAC! Big fan of your work.

I'm working on sending recorded video (original material) from OBS to Twitch and other destinations, which means I do have SRT files.

Using a VLC source, I can embed subtitles with the SRT, but they just appear as "burned in" and can't be toggled by the viewer.

Since this plugin is the only one I know that sends functional captions to Twitch, I was wondering if you knew of a way to embed SRT (or if it could be done with this plugin) on that caption track so that it works with the "native" Twitch captioning.

I'd love to talk more about it if you have the time. Thank you!

bost-ty

**Comment by bradnak** [comment]
Yeah, I think it would be cool if we could pull in subtitles from video sources, I once started captioning a video intro with the hopes it would be picked up by the plugin, but it wasn't and the captions appeared burned in for me too. I ended up not completing the captions on that intro because of that.

**Comment by ratwithacompiler** [comment]
This plugin is primarily for captioning audio via speech recognition, the actual embedding of the captions text into the video stream is all handled by OBS itself so a feature for forwarding captions from an existing video is mostly out of scope for this plugin. Would make most sense as either a media source plugin or standalone script I think.

**Comment by bost-ty** [comment]
Thank you! I'm looking at other solutions based on what you've told me. Knowing that you handle embedding the captions through OBS itself is very helpful.

(Closing.)
