### ISSUE TITLE
Cannot Configure

### ISSUE THREAD

**Issue by RippleInThePond** [ratwithacompiler/OBS-captions-plugin#98]
Reinstalled after OBSv28.0.0. Cannot open settings to configure. It gets as far as opening in the taskbar, but it is just a white box that I cannot fully open or interact with.
![Untitled](https://user-images.githubusercontent.com/112721695/188207335-232f16ff-072f-46ff-84d6-a0193b797c0e.png)

**Comment by ratwithacompiler** [comment]
You can try this one which has a reworked UI [Closed_Captions_Plugin__v0.29_Windows.zip](https://github.com/ratwithacompiler/OBS-captions-plugin/files/9480611/Closed_Captions_Plugin__v0.29_Windows.zip)

If that has the same issue check or upload logs.

**Comment by RippleInThePond** [comment]
Unfortunately, it's still an issue, but I did find a way around it. I just right-click the whited out settings tab, maximize it, and it magically starts working. It continues to open correctly unless I close and re-open OBS in which case I have to do it again. So, it's inconvenient but it no longer makes the plugin unable to be configured.
